### ISSUE TITLE
Panic Room Pro-Job Assault never ends

### ISSUE THREAD

**Issue by Jasorn** [payday-restoration/restoration-mod#185]
When Bile is waiting for you to clear the roof, the assault with the point of no return never ends, sat there for 20 minutes fighting cops and the assault never ended for him to come in and lift the panic room. Ended up failing

This is on the dev branch, as of June 25th version

**Comment by ImperatorStorm** [comment]
FYI, Assault ending is no longer tied to Bile arriving.
you need to manually clear out the roof for Bile to arrive.

**Comment by Jasorn** [comment]
If that's the case then I'm not sure what happened because me with 3 AI + 2 converted cops, we're killing cops non stop on the other rooftops and had the roof clear a few times throughout it

**Comment by Whurrhurr** [comment]
payday 2's hud is awful (and a downgrade in many aspects from PD:TH's) as PONRs in TH had their own hud element, in 2 it's part of the assault indicator now (which i guess makes sense when every instance of a PONR in loud is usually hunt+PONR but in resmod it just looks bad since most cases of a PONR in resmod usually isn't a hunt+PONR combo) and bile will not come in if there's more than 4 cops on the roof. he also won't pull the panic room out unless the smoke (from the hole made from the c4, not the smoke grenades being spammed at the roof access) is gone, the smoke going away takes 10 seconds (iirc, if it's not 10s then it's 30s) and then there also must be less than 4 cops on the roof.

**Comment by Jasorn** [comment]
Tried it again, the assault ended right before Bile came in with the magnet and he lowered it right away, so I guess I got lucky? If it is actually tied to number of cops and not assault anymore, I'll just mark it down as I wasn't good enough to clear them out
